language: node_js
node_js:
  - "14"
  - "16"
  - "18"

services:
  - mysql

before_install:
  - mysql -e 'CREATE DATABASE IF NOT EXISTS 1703_test;'

cache:
  directories:
    - node_modules

install:
  - npm ci

before_script:
  - cp .env.example .env
  - npm run build

script:
  - npm run test
  - npm run lint

after_success:
  - npm run coverage

notifications:
  email:
    on_success: change
    on_failure: always 